language: java

jdk: oraclejdk8

sudo: required

services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_65639c0ca27a_key -iv $encrypted_65639c0ca27a_iv
  -in .maven-settings.xml.enc -out .maven-settings.xml -d

install: mvn -B -Pdocker,oracle clean install
